nome=input("Qual seu nome? \n")
print("Endereço")
rua=input("Rua \n")
nun=int(input("Número \n"))
bairro=input("Bairro \n")
mun=input("Município \n")
uf=input("Estado \n")
print("=========================================")
print("Nome:\n",nome)
print("Endereço \n Rua:",rua,", Nº:",nun)
print("Bairro:",bairro)
print("Município \n",mun)
print("Estado \n",uf)
print("========================================= \n")
