nome=input("Qual seu nome? \n")
print("Endereço")
rua=input("Rua \n")
nun=int(input("Número \n"))
bairro=input("Bairro \n")
mun=input("Município \n")
uf=input("Estado \n")
print("=========================================")
print("Nome:\n",nome)
print("Endereço \n Rua:",rua,", Nº:",nun)
print("Bairro:",bairro)
print("Município \n",mun)
print("Estado \n",uf)
print("========================================= \n")
with open("005_cadastro.txt", "w", encoding="utf-8")as cadastro:
	cadastro.write("=========================================")
	cadastro.write("Nome:\n",nome)
	cadastro.write("Endereço \n Rua:",rua,", Nº:",nun)
	cadastro.write("Bairro:",bairro)
	cadastro.write("Município \n",mun)
	cadastro.write("Estado \n",uf)
	cadastro.write("Estado \n",uf)
print("arquivo 005_cadastro.txt criado")
